name: Deploy Firy Streak Web App

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/**'

jobs:
  build_and_deploy:
    # Permissões necessárias para a Action de autenticação da Google
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      # Passo 1
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Passo 2
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIRY_STREAK_APP }}' # Verifique se este nome de secret está correto!

      # Passo 3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2' # Use sua versão
          channel: 'stable'
          cache: true
      
      # Passo 4
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      # Passo 5
      - name: Install FlutterFire CLI
        run: dart pub global activate flutterfire_cli

      # Passo 6
      - name: Generate Firebase Options
        run: |
          flutterfire configure \
            --project=firy-streak \
            --platforms=web \
            --web-app-id=${{ secrets.FIREBASE_WEB_APP_ID }} \
            --yes
      
      # Passo 7
      - name: Install Project Dependencies
        run: flutter pub get

      # Passo 8
      - name: Build Web App
        run: flutter build web --release

      # Passo 9
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIRY_STREAK_APP }}' # Verifique se este nome de secret está correto!
          projectId: 'firy-streak'
          channelId: live
